
title: Informe practica 10 DSI
author: Joel Aday Dorta Hernandez 
email: alu0100987584@ull.edu.es
theme: minima
description: Informe de la practica 10 de la asignatura DSI

show_excerpts: true # set to false to remove excerpts on the homepage
